import {useEffect,useState} from 'react';
import {Routes,Route,NavLink,Link,useLocation} from 'react-router-dom';
import {motion} from 'framer-motion';
import {ArrowRight,ChevronDown,ChevronUp,Factory,Globe2,Mail,MapPin,Menu,Phone,Radio,Shield,Target,Users, X,Zap,Rocket, Cpu, Crosshair, CheckCircle2, Building2, Newspaper, BriefcaseBusiness} from 'lucide-react';

const A='/images/';
const nav=[['About','/about'],['Capabilities','/capabilities'],['Solutions','/solutions'],['Industries','/industries'],['Infrastructure','/infrastructure'],['News','/news'],['Careers','/careers']];

const capabilities=[
 {icon:Shield,title:'Defence Capabilities',image:'capabilities/precision-engineering.svg',text:'Defence-grade engineering services and integrated solutions for rugged, mission-critical environments.'},
 {icon:Rocket,title:'Aerospace Systems',image:'capabilities/aerospace-systems.svg',text:'Aerospace platforms, structures, subsystems and technology integration for defence applications.'},
 {icon:Cpu,title:'Defence Electronics & Embedded',image:'capabilities/electronics.svg',text:'Rugged defence electronics, embedded control, computing and intelligent interfaces.'},
 {icon:Crosshair,title:'Precision Defence Manufacturing',image:'capabilities/precision-engineering.svg',text:'Precision fabrication, assemblies, fixtures and manufacturing for demanding defence applications.'},
 {icon:Radio,title:'Surveillance & Sensing',image:'capabilities/systems-integration.svg',text:'Defence sensing, surveillance, communications and situational-awareness building blocks.'},
 {icon:Zap,title:'Systems Integration',image:'capabilities/embedded-digital.svg',text:'Hardware, software and electro-mechanical integration for defence systems from concept to test.'}
];
const solutions=[
 ['01','Defence Rugged Electronics','products/rugged-electronics.svg','Mission-grade defence electronics and control assemblies designed around customer requirements.'],
 ['02','Defence Mission Computing','products/mission-computing.svg','Modular defence computing and digital interfaces for field and platform applications.'],
 ['03','Defence Surveillance Systems','products/surveillance-systems.svg','Sensor and surveillance building blocks for defence monitoring and situational awareness.'],
 ['04','Precision Defence Assemblies','products/precision-assemblies.svg','Precision mechanical and electro-mechanical defence assemblies with controlled quality.'],
 ['05','Defence Engineering Prototypes','capabilities/research-development.svg','Rapid defence prototyping and design iterations to accelerate technology validation.'],
 ['06','Defence Integration & Testing','capabilities/systems-integration.svg','Structured integration, verification and test support for complex defence systems.']
];
const industries=[
 ['Defence','industries/defence.svg','Land, naval and strategic defence applications requiring rugged defence engineering.'],
 ['Aerospace & Defence','industries/aerospace.svg','Defence aerospace platforms, subsystems and support technologies.'],
 ['Defence Electronics','industries/electronics.svg','Embedded, electronic and digital defence systems for high-reliability environments.'],
 ['Defence Security & Surveillance','industries/security.svg','Defence technology for monitoring, sensing, communications and security applications.']
];
const facility=[
 ['Defence Manufacturing','facility/manufacturing.svg','Precision defence fabrication and production workflows.'],['Defence Engineering Lab','facility/engineering-lab.svg','Defence design, prototyping and validation environment.'],['Defence Quality & Test','facility/quality.svg','Defence inspection, verification and controlled test practices.'],['Defence Integration','facility/integration.svg','System-level defence assembly and integration capabilities.']
];
const news=[
 ['Defence Engineering first','Building an indigenous defence engineering platform for mission-critical technology.','news/engineering.svg'],
 ['Defence Innovation pipeline','From prototype thinking to scalable defence product architecture.','news/innovation.svg'],
 ['Defence Industry focus','Developing defence capabilities aligned to India’s strategic defence technology ecosystem.','news/industry.svg']
];

function ScrollTop(){const {pathname}=useLocation();useEffect(()=>window.scrollTo({top:0,behavior:'instant'}),[pathname]);return null}
function Header(){const [open,setOpen]=useState(false);return <header className="header"><div className="container nav"><Link to="/" className="brand" onClick={()=>setOpen(false)}><img src="/logo.png" alt="Aeronit Defence Private Limited"/></Link><nav className={open?'navlinks open':'navlinks'}>{nav.map(([n,p])=><NavLink key={p} to={p} onClick={()=>setOpen(false)}>{n}</NavLink>)}<Link className="navbutton" to="/contact" onClick={()=>setOpen(false)}>Contact <ArrowRight size={16}/></Link></nav><button className="menubtn" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></header>}
function Footer(){return <footer><div className="container footer-main"><div><Link to="/" aria-label="Aeronit Defence Private Limited home"><img src="/logo.png" className="footer-logo" alt="Aeronit Defence Private Limited"/></Link><p>Indigenous defence, aerospace and engineering capabilities built around precision, resilience and purpose.</p></div><div><h4>Explore</h4>{nav.slice(0,5).map(([n,p])=><Link key={p} to={p}>{n}</Link>)}</div><div><h4>Company</h4><Link to="/news">News & Updates</Link><Link to="/careers">Careers</Link><Link to="/contact">Contact</Link><Link to="/privacy">Privacy</Link></div><div><h4>Reach us</h4><span className="footer-contact"><MapPin size={15}/> 968, Kondhala, Desaiganj (Vadasa), Gadchiroli, Maharashtra – 441207</span><span className="footer-contact"><Mail size={15}/> info@aeronitdefence.com</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Aeronit Defence Private Limited. All rights reserved.</span><span>Defence · Aerospace · Engineering · Technology</span></div></footer>}
function PageHero({kicker,title,children,image}){return <section className="pagehero"><div className="pagehero-art" style={{backgroundImage:`url(${A}${image||'hero/mission-systems.svg'})`}}/><div className="container pagehero-inner"><div className="eyebrow"><span/>{kicker}</div><h1>{title}</h1>{children&&<p>{children}</p>}</div></section>}
function Reveal({children,delay=0,className=''}){return <motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.55,delay}}>{children}</motion.div>}
function Home(){return <>
  {/* Defence banner at the top */}
  <div className="defence-banner">
    <div className="container">
      <div className="banner-inner">
        <Shield size={20}/>
        <span>INDIGENOUS DEFENCE · AEROSPACE · ELECTRONIC SYSTEMS · MISSION-CRITICAL ENGINEERING</span>
      </div>
    </div>
  </div>
  <section className="hero">
    <div className="hero-bg"/>
    <div className="hero-overlay"/>
    <div className="hero-lines"/>
    <div className="container hero-inner">
      <div className="hero-content">
        <Reveal>
          <div className="eyebrow"><span/>DEFENCE SOLUTIONS</div>
          <h1>Built for <em>mission-critical</em> defence systems.</h1>
          <p>Aeronit Defence Private Limited delivers technology-led defence capabilities — from precision engineering and rugged electronics to aerospace subsystems and integrated mission platforms.</p>
          <div className="actions">
            <Link className="button" to="/capabilities">Explore defence capabilities <ArrowRight size={18}/></Link>
            <Link className="button ghost" to="/contact">Start a conversation</Link>
          </div>
        </Reveal>
      </div>
    </div>
    <div className="hero-scroll">SCROLL <ChevronDown size={15}/></div>
  </section><section className="section"><div className="container split"><Reveal><div><div className="eyebrow dark"><span/>WHO WE ARE</div><h2>Built around <em>precision, resilience and purpose.</em></h2><p className="lead">Aeronit is envisioned as an indigenous defence technology and engineering partner for the defence ecosystem. Our model brings together defence design thinking, precision defence engineering, systems integration and dependable execution.</p><Link className="textlink" to="/about">Discover Aeronit <ArrowRight size={17}/></Link></div></Reveal><div className="feature-stack"><Reveal delay={.05}><img src={A+'hero/defence-aerospace.svg'} alt="Defence capabilities"/></Reveal><div className="floating-note"><Shield size={22}/><b>Built for mission-critical environments</b><span>Defence engineering with quality and reliability at the centre.</span></div></div></div></section>
 <section className="section soft"><div className="container"><div className="sectionhead"><div><div className="eyebrow dark"><span/>DEFENCE CAPABILITIES</div><h2>Technology that works <em>when it matters.</em></h2></div><Link className="textlink" to="/capabilities">View all defence capabilities <ArrowRight size={17}/></Link></div><div className="cards six">{capabilities.map((c,i)=><Reveal key={c.title} delay={i*.06}><Card data={c}/></Reveal>)}</div></div></section>
 <section className="statement"><div className="statement-art"/><div className="container"><div className="eyebrow"><span/>MADE IN INDIA · BUILT FOR THE DEFENCE MISSION</div><h2>From <em>idea</em> to mission-ready defence system.</h2><p>Defence engineering, integration and execution with a relentless focus on quality.</p><Link className="button light" to="/solutions">Explore defence solutions <ArrowRight size={18}/></Link></div></section>
 <section className="section"><div className="container"><div className="sectionhead"><div><div className="eyebrow dark"><span/>DEFENCE SECTORS</div><h2>Focused on <em>strategic defence applications.</em></h2></div></div><div className="industrygrid">{industries.map((x,i)=><Reveal key={x[0]} delay={i*.05}><Link to="/industries" className="industrycard"><img src={A+x[1]}/><div><b>{x[0]}</b><span>{x[2]}</span></div><ArrowRight size={18}/></Link></Reveal>)}</div></div></section>
 </>}
function Card({data}){const Icon=data.icon;return <article className="card"><img src={A+data.image} alt=""/><div className="cardbody">{Icon&&<Icon size={28}/>}<h3>{data.title}</h3><p>{data.text}</p><span className="circlearrow"><ArrowRight size={16}/></span></div></article>}
function About(){return <><PageHero kicker="ABOUT AERONIT" title={<>Defence <em>capabilities.</em></>} image="hero/defence-aerospace.svg">A defence technology and engineering company being built for the evolving needs of India's strategic defence industries.</PageHero><section className="section"><div className="container split"><div><div className="eyebrow dark"><span/>OUR STORY</div><h2>Purpose-led defence engineering with an <em>Indian point of view.</em></h2></div><div><p className="lead">Aeronit Defence Private Limited is focused on developing a dependable defence engineering platform for defence, aerospace, defence electronics and related mission-critical applications.</p><p>We believe meaningful capability comes from disciplined defence engineering, strong quality systems, customer understanding and the ability to turn complex requirements into practical defence solutions.</p></div></div></section><section className="section soft"><div className="container"><div className="values"><Value icon={Target} t="Mission" d="Deliver dependable technology and engineering for mission-critical environments."/><Value icon={Globe2} t="Vision" d="Build globally competitive Indian defence engineering capabilities."/><Value icon={Users} t="People" d="Create a culture of ownership, learning, integrity and technical excellence."/><Value icon={CheckCircle2} t="Quality" d="Treat reliability, traceability and continuous improvement as core disciplines."/></div></div></section><section className="section"><div className="container split image-split"><img src={A+'facility/engineering-lab.svg'} alt="Aeronit defence engineering lab"/><div><div className="eyebrow dark"><span/>OUR APPROACH</div><h2>Think. Engineer. <em>Integrate.</em></h2><p className="lead">Our workflow is designed to shorten the distance between an idea and a validated defence engineering outcome.</p><div className="steps"><b>01 <span>Understand</span></b><b>02 <span>Design</span></b><b>03 <span>Prototype</span></b><b>04 <span>Integrate & test</span></b></div></div></div></section></>}
function Value({icon:Icon,t,d}){return <div className="value"><Icon/><h3>{t}</h3><p>{d}</p></div>}
function Capabilities(){return <><PageHero kicker="DEFENCE CAPABILITIES" title={<>Deep defence engineering. Clear outcomes.</>} image="hero/defence-aerospace.svg">A multidisciplinary defence capability stack designed for defence and other high-reliability technology environments.</PageHero><section className="section"><div className="container"><div className="cards six">{capabilities.map((c,i)=><Reveal key={c.title} delay={(i%3)*.06}><Card data={c}/></Reveal>)}</div></div></section><section className="section soft"><div className="container split"><div><div className="eyebrow dark"><span/>DEFENCE ENGINEERING FLOW</div><h2>One team across the <em>defence technology lifecycle.</em></h2></div><div className="flow"><span>Requirement</span><ArrowRight/><span>Design</span><ArrowRight/><span>Prototype</span><ArrowRight/><span>Integrate</span><ArrowRight/><span>Test</span></div></div></section></>}
function Solutions(){return <><PageHero kicker="DEFENCE SOLUTIONS" title={<>Built as <em>modular</em> defence technology.</>} image="hero/mission-systems.svg">Defence solutions are structured as adaptable engineering building blocks so defence requirements can evolve without losing discipline.</PageHero><section className="section"><div className="container solutiongrid">{solutions.map((s,i)=><Reveal key={s[1]} delay={(i%3)*.05}><article className="solution"><img src={A+s[2]} alt=""/><div><small>{s[0]}</small><h3>{s[1]}</h3><p>{s[3]}</p><Link to="/contact" className="textlink">Discuss requirement <ArrowRight size={16}/></Link></div></article></Reveal>)}</div></section><section className="section darksection"><div className="container split"><div><div className="eyebrow"><span/>CUSTOM ENGINEERING</div><h2>Have a requirement that doesn't fit a catalogue?</h2></div><div><p>We can structure a technical discussion around your platform, environment, interface, performance and integration needs.</p><Link className="button light" to="/contact">Talk to engineering <ArrowRight size={18}/></Link></div></div></section></>}
function Industries(){return <><PageHero kicker="DEFENCE INDUSTRIES" title={<>Technology for <em>strategic</em> defence sectors.</>} image="hero/mission-systems.svg">Aeronit is designed to support defence applications where reliability, integration and engineering discipline matter.</PageHero><section className="section"><div className="container industrylarge">{industries.map((x,i)=><Reveal key={x[0]} delay={i*.06}><article><img src={A+x[1]} alt=""/><div><div className="eyebrow dark"><span/>0{i+1}</div><h2>{x[0]}</h2><p>{x[2]}</p><Link className="textlink" to="/contact">Explore a project <ArrowRight size={17}/></Link></div></article></Reveal>)}</div></section></>}
function Infrastructure(){return <><PageHero kicker="DEFENCE INFRASTRUCTURE" title={<>Defence capability needs a <em>strong foundation.</em></>} image="facility/manufacturing.svg">A structured environment for defence engineering, manufacturing, quality and integration.</PageHero>
  <section className="section"><div className="container"><div className="sectionhead"><div><div className="eyebrow dark"><span/>FACILITIES</div><h2>Designed for <em>controlled defence execution.</em></h2></div><p>Our infrastructure roadmap is centered on disciplined defence engineering workflows, traceability, inspection and system integration.</p></div><div className="facilitygrid">{facility.map((x,i)=><Reveal key={x[0]} delay={i*.05}><article><img src={A+x[1]} alt={x[0]}/><div><h3>{x[0]}</h3><p>{x[2]}</p></div></article></Reveal>)}</div></div></section>
  <section className="section soft"><div className="container stats"><div><b>01</b><span>Defence Engineering</span></div><div><b>02</b><span>Defence Manufacturing</span></div><div><b>03</b><span>Defence Quality</span></div><div><b>04</b><span>Defence Integration</span></div></div></section></>}
function News(){return <><PageHero kicker="DEFENCE NEWS & UPDATES" title={<>The Aeronit <em>journal.</em></>} image="news/innovation.svg">Company stories, defence engineering thinking and milestones will live here as the Aeronit defence platform grows.</PageHero><section className="section"><div className="container newsgrid">{news.map((n,i)=><Reveal key={n[0]} delay={i*.07}><article><img src={A+n[2]} alt=""/><div className="newscopy"><small>INSIGHT · AERONIT</small><h3>{n[0]}</h3><p>{n[1]}</p><Link className="textlink" to="/contact">Talk to us <ArrowRight size={16}/></Link></div></article></Reveal>)}</div></section></>}
function Careers(){return <><PageHero kicker="DEFENCE CAREERS" title={<>Build what <em>matters.</em></>} image="facility/engineering-lab.svg">Join a team where defence engineering ownership, learning and mission impact are part of the work.</PageHero><section className="section"><div className="container split"><div><div className="eyebrow dark"><span/>WORK WITH US</div><h2>Technical ambition needs <em>great people.</em></h2><p className="lead">We are building a culture for engineers, technicians, programme thinkers and business professionals who want to contribute to India's strategic technology ecosystem.</p></div><div className="careerbox"><BriefcaseBusiness/><h3>Open applications</h3><p>Tell us about your skills, experience and the kind of work you want to build.</p><Link className="button" to="/contact">Send your profile <ArrowRight size={18}/></Link></div></div></section><section className="section soft"><div className="container values"><Value icon={Target} t="Ownership" d="Take responsibility from requirement to outcome."/><Value icon={Zap} t="Learning" d="Stay curious, technical and continuously improving."/><Value icon={Users} t="Teamwork" d="Build better outcomes through cross-functional collaboration."/><Value icon={Shield} t="Integrity" d="Do the right thing for customers, colleagues and the mission."/></div></section></>}
function Contact(){const [form,setForm]=useState({name:'',email:'',phone:'',message:''}),[status,setStatus]=useState('');const API=import.meta.env.VITE_API_BASE||'';async function submit(e){e.preventDefault();setStatus('Sending…');try{const r=await fetch(API+'/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to send');setStatus('Thank you. Your enquiry has been received.');setForm({name:'',email:'',phone:'',message:''})}catch(err){setStatus(err.message+' Please email info@aeronitdefence.com directly.')}}return <><PageHero kicker="DEFENCE CONTACT" title={<>Let's build <em>what's next.</em></>} image="hero/defence-aerospace.svg">Have a requirement, partnership opportunity or defence technology challenge? Send us a brief.</PageHero><section className="section"><div className="container contactgrid"><div><div className="eyebrow dark"><span/>AERONIT DEFENCE PRIVATE LIMITED</div><h2>Start a <em>conversation.</em></h2><p className="lead">Our team can take an initial requirement and turn it into a structured technical discussion.</p><div className="contactitems"><div><MapPin/><b>Establishment address</b><span>968, Kondhala, Desaiganj (Vadasa), Gadchiroli, Maharashtra – 441207, India</span></div><div><Mail/><b>Email</b><span>info@aeronitdefence.com</span></div><div><Phone/><b>Phone</b><span>+91 — add official number before launch</span></div></div></div><form className="form" onSubmit={submit}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="formrow"><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label>Requirement<textarea required rows="7" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><button className="button" type="submit">Send enquiry <ArrowRight size={18}/></button>{status&&<p className="status">{status}</p>}</form></div></section></>}
function Privacy(){return <><PageHero kicker="LEGAL" title={<>Privacy <em>notice.</em></>} image="hero/defence-aerospace.svg"/><section className="section legal"><div className="container"><h2>Privacy & website use</h2><p>This starter policy explains that information submitted through this website may be used to respond to enquiries and operate the website. Replace this text with your reviewed legal policy before production launch.</p><h3>Information submitted</h3><p>Contact details and enquiry content are used for legitimate business communication and should be handled securely.</p><h3>Contact</h3><p>For privacy questions, contact Aeronit Defence Private Limited through the official company email.</p></div></section></>}
function NotFound(){return <PageHero kicker="404" title={<>Page not <em>found.</em></>}><Link className="button light" to="/">Return home <ArrowRight size={18}/></Link></PageHero>}
function App(){return <><ScrollTop/><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/capabilities" element={<Capabilities/>}/><Route path="/solutions" element={<Solutions/>}/><Route path="/industries" element={<Industries/>}/><Route path="/infrastructure" element={<Infrastructure/>}/><Route path="/news" element={<News/>}/><Route path="/careers" element={<Careers/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy" element={<Privacy/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></>}
export default App;
